name: Deploy React App to EC2

on:
  push:
    branches:
      - main  # change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.EC2_HOST }}         # EC2 IP or hostname
        username: ubuntu                      # or your SSH user
        key: ${{ secrets.EC2_SSH_KEY }}      # private SSH key stored in GitHub Secrets
        script: |
          cd /home/ubuntu/your-react-app
          ./deploy.sh
